import Foundation

// MARK: - ResolvedApiEndpoint

/// 已解析的 API 端点（可直接用于构建 URLRequest）
/// Resolved API endpoint (ready for building URLRequest)
///
/// 由 `ApiEndpointResolver` 解析 `ApiEndpoint` 后生成，包含最终路径、版本和参数。
/// Generated by `ApiEndpointResolver` from `ApiEndpoint`, contains final path, version, and parameters.
struct ResolvedApiEndpoint {
    /// API 名称（如 "SYNO.AudioStation.Song"）
    /// API name (e.g. "SYNO.AudioStation.Song")
    let name: String

    /// API 方法（如 "list"、"getinfo"）
    /// API method (e.g. "list", "getinfo")
    let method: String

    /// 实际使用版本（已通过 Clamp 到服务器支持范围）
    /// Actual version (clamped to server-supported range)
    let version: Int

    /// 合并后的请求参数（含 api / version / method 等公共参数）
    /// Merged request parameters (including common params: api / version / method)
    let parameters: ApiParameters

    /// API 路径（如 "/webapi/entry.cgi"）
    /// API path (e.g. "/webapi/entry.cgi")
    let apiPath: String

    /// 是否需要在 Cookie 中携带认证信息（SID/DID）
    /// Whether authentication (SID/DID) is required in Cookie header
    let requireAuthCookie: Bool

    /// 是否需要在 URL Query 中携带 _sid 参数
    /// Whether `_sid` parameter is required in URL query string
    let requireAuthQuery: Bool
}
